### ISSUE TITLE
module 'cv2.cv2' has no attribute 'SIFT_create'

### ISSUE THREAD

**Issue by Rlezzo** [Mzmba/dragon_killer#1]
![S7@{)UUBK2% (KT9X4X79U](https://user-images.githubusercontent.com/86238734/193302203-0bc43eec-648b-4108-9267-9ccf20e95e92.png)
无法正常使用

**Comment by Mzmba** [comment]
你的Opencv版本有问题，修改Opencv版本与此一致
opencv-contrib-python     4.6.0.66
opencv-python             4.6.0.66
opencv-python-headless    4.1.2.30
或者直接修改代码，请参考
https://blog.csdn.net/weixin_49076390/article/details/121228821
https://blog.csdn.net/qq_36584673/article/details/121978426
